name: Renovation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "15 2 * * 0"  # every Sunday at 2:15 AM
  workflow_dispatch:  # allows manual triggering of the workflow

jobs:
  update-dependencies:

    name: "Update Dependencies"
    runs-on: "ubuntu-24.04"

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.20
        with:
          #docker-cmd-file: .github/renovate-entrypoint.sh
          #docker-user: root
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: info
